### ISSUE TITLE
EDMC plugin EDR does not work

### ISSUE THREAD

**Issue by netchild** [EDDiscovery/EDD-EDMC#11]
https://edrecon.com/edmc-plugin

.\eddedmc.exe : Traceback (most recent call last):
In Zeile:1 Zeichen:1
+ .\eddedmc.exe 2>&1 >'D:\ED\EDD-EDMC.txt'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "plug.pyc", line 95, in __init__
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Alexa\AppData\Local\EDD-EDMC\plugins\EDR-v1.1.0\load.py", line 7, in <module>
    from edrclient import EDRClient
  File "C:\Users\Alexa\AppData\Local\EDD-EDMC\plugins\EDR-v1.1.0\edrclient.py", line 26, in <module>
    from audiofeedback import AudioFeedback
  File "C:\Users\Alexa\AppData\Local\EDD-EDMC\plugins\EDR-v1.1.0\audiofeedback.py", line 34, in <module>
    import winsound
ModuleNotFoundError: No module named 'winsound'

**Comment by robbyxp1** [comment]
winsound is not part of EDMC, no idea how EDR works and why it thinks it can import it.

**Comment by netchild** [comment]
winsound.pyd is in the root of my EDMarketConnector install folder. I did not copy it there in the EDR install. So I assume it comes with EDMC.

**Comment by robbyxp1** [comment]
I suggest you use the real EDMC for now, EDD-EDMC is now out of date with their current stuff.
