### ISSUE TITLE
EDMC Plugin EDMC-Canonn does not load

### ISSUE THREAD

**Issue by ghost** [EDDiscovery/EDD-EDMC#9]
```
c:\Program Files\EDD-EDMC>eddedmc.exe
APP Values Are: EDD-EDMC 4.0.0.0 2021-05-21T16:45:48
Setup Is: nostdout False packaged console_exe
DLL folder c:\Program Files\EDD-EDMC\EDMCHarness.dll to C:\Users\gunhed\AppData\Local\EDDLite\DLL\EDMCHarness.dll
DLL folder c:\Program Files\EDD-EDMC\EDMCHarness.dll to C:\Users\gunhed\AppData\Local\EDDiscovery\DLL\EDMCHarness.dll
Check c:\Program Files\EDD-EDMC\plugins
Check C:\Users\gunhed\AppData\Local\EDD-EDMC\plugins
Plugin EDMC-Screenshot.disabled
plugin EDMC-Screenshot disabled
Plugin EDMC-Canonn-6.0.0
Adding EDMC-Canonn-6.0.0
loading plugin EDMC-Canonn-6_0_0 from "C:\Users\gunhed\AppData\Local\EDD-EDMC\plugins\EDMC-Canonn-6.0.0\load.py"
Added EDMC-Canonn-6.0.0
Plugin edmc-L3-37
Adding edmc-L3-37
loading plugin edmc-L3-37 from "C:\Users\gunhed\AppData\Local\EDD-EDMC\plugins\edmc-L3-37\load.py"
L3-37 started
Added edmc-L3-37
Plugin EDMCJumpSpeed-master
Adding EDMCJumpSpeed-master
loading plugin EDMCJumpSpeed-master from "C:\Users\gunhed\AppData\Local\EDD-EDMC\plugins\EDMCJumpSpeed-master\load.py"
Added EDMCJumpSpeed-master
Plugin EDSM-RSE
Adding EDSM-RSE
loading plugin EDSM-RSE from "C:\Users\gunhed\AppData\Local\EDD-EDMC\plugins\EDSM-RSE\load.py"
Traceback (most recent call last):
  File "plug.pyc", line 97, in __init__
  File "C:\Users\gunhed\AppData\Local\EDD-EDMC\plugins\EDSM-RSE\load.py", line 143, in plugin_start3
    plugin_start(plugin_dir)
  File "C:\Users\gunhed\AppData\Local\EDD-EDMC\plugins\EDSM-RSE\load.py", line 116, in plugin_start
    settings = config.get_int(this.CONFIG_MAIN) or 0  # default setting
AttributeError: 'Config' object has no attribute 'get_int'
Traceback (most recent call last):
  File "plug.pyc", line 128, in get_app
  File "C:\Users\gunhed\AppData\Local\EDD-EDMC\plugins\EDMC-Canonn-6.0.0\load.py", line 150, in plugin_app
    this.news = news.CanonnNews(table, 0)
  File "C:\Users\gunhed\AppData\Local\EDD-EDMC\plugins\EDMC-Canonn-6.0.0\canonn\news.py", line 96, in __init__
    self.hidden = tk.IntVar(value=config.get_int("HideNews"))
AttributeError: 'Config' object has no attribute 'get_int'
Failed to load route data
Chat Viewer loaded
Recon Limpet Controllers is missing!
Research Limpet Controller is missing!
L3-37 loaded
```
... and now EDD-EDMC is up and running (without the mentioned plugin).

**Comment by robbyxp1** [comment]
After the odyssey situation, and EDMC stops so fast, i'll bring it up to spec

**Comment by ghost** [comment]
Thanks, no hurry. I appreciate your effort to link EDD and EDMC, very useful.
